name: Build and Deploy openvpn for GreenDev

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - hotfix/*
  #   tags:
  #     - "*.*.*"

run-name: Deploy by @${{ github.actor }} at ${{ github.event_name }} ${{ github.sha }}

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          dev-branch: develop

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GD_REGISTRY_SERVER }}
          username: ${{ secrets.GD_REGISTRY_USERNAME }}
          password: ${{ secrets.GD_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: "Dockerfile"
          context: "{{defaultContext}}:."
          tags: ${{secrets.GD_REGISTRY_SERVER}}/openvpn:${{ steps.version.outputs.version }}
